//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniJira.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniJira.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        internal static string Board_ColumnDone {
            get {
                return ResourceManager.GetString("Board.ColumnDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN PROGRESS.
        /// </summary>
        internal static string Board_ColumnInProgress {
            get {
                return ResourceManager.GetString("Board.ColumnInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO DO.
        /// </summary>
        internal static string Board_ColumnToDo {
            get {
                return ResourceManager.GetString("Board.ColumnToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load tasks: {0}.
        /// </summary>
        internal static string Board_FailedToLoad {
            get {
                return ResourceManager.GetString("Board.FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading board....
        /// </summary>
        internal static string Board_LoadingBoard {
            get {
                return ResourceManager.GetString("Board.LoadingBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks.
        /// </summary>
        internal static string Board_NoTasks {
            get {
                return ResourceManager.GetString("Board.NoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        internal static string Board_Task {
            get {
                return ResourceManager.GetString("Board.Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        internal static string Board_Tasks {
            get {
                return ResourceManager.GetString("Board.Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        internal static string Board_Title {
            get {
                return ResourceManager.GetString("Board.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNTS.
        /// </summary>
        internal static string Category_Accounts {
            get {
                return ResourceManager.GetString("Category.Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILLING.
        /// </summary>
        internal static string Category_Billing {
            get {
                return ResourceManager.GetString("Category.Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORMS.
        /// </summary>
        internal static string Category_Forms {
            get {
                return ResourceManager.GetString("Category.Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAL.
        /// </summary>
        internal static string Category_General {
            get {
                return ResourceManager.GetString("Category.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Board.
        /// </summary>
        internal static string Common_Back {
            get {
                return ResourceManager.GetString("Common.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Task.
        /// </summary>
        internal static string Common_CreateTask {
            get {
                return ResourceManager.GetString("Common.CreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Common_Edit {
            get {
                return ResourceManager.GetString("Common.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string Common_Error {
            get {
                return ResourceManager.GetString("Common.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Common_Loading {
            get {
                return ResourceManager.GetString("Common.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating....
        /// </summary>
        internal static string CreateTask_Creating {
            get {
                return ResourceManager.GetString("CreateTask.Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description *.
        /// </summary>
        internal static string CreateTask_Description {
            get {
                return ResourceManager.GetString("CreateTask.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the task in detail....
        /// </summary>
        internal static string CreateTask_DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("CreateTask.DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string CreateTask_Priority {
            get {
                return ResourceManager.GetString("CreateTask.Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Title *.
        /// </summary>
        internal static string CreateTask_TaskTitle {
            get {
                return ResourceManager.GetString("CreateTask.TaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use clear, concise titles that describe the task at a glance.
        /// </summary>
        internal static string CreateTask_Tip1 {
            get {
                return ResourceManager.GetString("CreateTask.Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide detailed descriptions to give context and requirements.
        /// </summary>
        internal static string CreateTask_Tip2 {
            get {
                return ResourceManager.GetString("CreateTask.Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set priority based on urgency and importance.
        /// </summary>
        internal static string CreateTask_Tip3 {
            get {
                return ResourceManager.GetString("CreateTask.Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break down large tasks into smaller, manageable ones.
        /// </summary>
        internal static string CreateTask_Tip4 {
            get {
                return ResourceManager.GetString("CreateTask.Tip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for creating great tasks.
        /// </summary>
        internal static string CreateTask_TipsTitle {
            get {
                return ResourceManager.GetString("CreateTask.TipsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Task.
        /// </summary>
        internal static string CreateTask_Title {
            get {
                return ResourceManager.GetString("CreateTask.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter task title.
        /// </summary>
        internal static string CreateTask_TitlePlaceholder {
            get {
                return ResourceManager.GetString("CreateTask.TitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        internal static string Language_Croatian {
            get {
                return ResourceManager.GetString("Language.Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language.English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string Language_SelectLanguage {
            get {
                return ResourceManager.GetString("Language.SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog.
        /// </summary>
        internal static string Nav_Backlog {
            get {
                return ResourceManager.GetString("Nav.Backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        internal static string Nav_Board {
            get {
                return ResourceManager.GetString("Nav.Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Nav_Reports {
            get {
                return ResourceManager.GetString("Nav.Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        internal static string Nav_Timeline {
            get {
                return ResourceManager.GetString("Nav.Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string TaskDetail_Created {
            get {
                return ResourceManager.GetString("TaskDetail.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        internal static string TaskDetail_DeleteConfirmation {
            get {
                return ResourceManager.GetString("TaskDetail.DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Task.
        /// </summary>
        internal static string TaskDetail_DeleteTask {
            get {
                return ResourceManager.GetString("TaskDetail.DeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone..
        /// </summary>
        internal static string TaskDetail_DeleteWarning {
            get {
                return ResourceManager.GetString("TaskDetail.DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TaskDetail_Description {
            get {
                return ResourceManager.GetString("TaskDetail.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string TaskDetail_Details {
            get {
                return ResourceManager.GetString("TaskDetail.Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        internal static string TaskDetail_EditTask {
            get {
                return ResourceManager.GetString("TaskDetail.EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete task: {0}.
        /// </summary>
        internal static string TaskDetail_FailedToDelete {
            get {
                return ResourceManager.GetString("TaskDetail.FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load task: {0}.
        /// </summary>
        internal static string TaskDetail_FailedToLoad {
            get {
                return ResourceManager.GetString("TaskDetail.FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save changes: {0}.
        /// </summary>
        internal static string TaskDetail_FailedToSave {
            get {
                return ResourceManager.GetString("TaskDetail.FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update task: {0}.
        /// </summary>
        internal static string TaskDetail_FailedToUpdate {
            get {
                return ResourceManager.GetString("TaskDetail.FailedToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update status: {0}.
        /// </summary>
        internal static string TaskDetail_FailedToUpdateStatus {
            get {
                return ResourceManager.GetString("TaskDetail.FailedToUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading task....
        /// </summary>
        internal static string TaskDetail_LoadingTask {
            get {
                return ResourceManager.GetString("TaskDetail.LoadingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string TaskDetail_Priority {
            get {
                return ResourceManager.GetString("TaskDetail.Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Status Change.
        /// </summary>
        internal static string TaskDetail_QuickStatusChange {
            get {
                return ResourceManager.GetString("TaskDetail.QuickStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string TaskDetail_Saving {
            get {
                return ResourceManager.GetString("TaskDetail.Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string TaskDetail_Status {
            get {
                return ResourceManager.GetString("TaskDetail.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task not found.
        /// </summary>
        internal static string TaskDetail_TaskNotFound {
            get {
                return ResourceManager.GetString("TaskDetail.TaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string TaskDetail_Updated {
            get {
                return ResourceManager.GetString("TaskDetail.Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string TaskPriority_High {
            get {
                return ResourceManager.GetString("TaskPriority.High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string TaskPriority_Low {
            get {
                return ResourceManager.GetString("TaskPriority.Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string TaskPriority_Medium {
            get {
                return ResourceManager.GetString("TaskPriority.Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string TaskStatus_Done {
            get {
                return ResourceManager.GetString("TaskStatus.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string TaskStatus_InProgress {
            get {
                return ResourceManager.GetString("TaskStatus.InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Do.
        /// </summary>
        internal static string TaskStatus_ToDo {
            get {
                return ResourceManager.GetString("TaskStatus.ToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        internal static string Validation_DescriptionRequired {
            get {
                return ResourceManager.GetString("Validation.DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the validation errors above..
        /// </summary>
        internal static string Validation_FixErrors {
            get {
                return ResourceManager.GetString("Validation.FixErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid task ID.
        /// </summary>
        internal static string Validation_InvalidTaskId {
            get {
                return ResourceManager.GetString("Validation.InvalidTaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid task status.
        /// </summary>
        internal static string Validation_InvalidTaskStatus {
            get {
                return ResourceManager.GetString("Validation.InvalidTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        internal static string Validation_TitleRequired {
            get {
                return ResourceManager.GetString("Validation.TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred: {0}.
        /// </summary>
        internal static string Validation_UnexpectedError {
            get {
                return ResourceManager.GetString("Validation.UnexpectedError", resourceCulture);
            }
        }
    }
}
